
[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.7.0"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.2.0"

[[constraint]]
  name = "github.com/oklog/run"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0"

[prune]
  go-tests = true
  unused-packages = true
